version: '3'

services:
  growchildren-api:
    container_name: growchildren-api
    image: growchildren-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - 'postgres'

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata_growchildren:/var/lib/postgresql/data

volumes:
  pgdata_growchildren:
    driver: local